version: "3.9"

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8000:8000"
    env_file:
    - .env
    depends_on:
    - jaeger
    - prometheus
    - ollama

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
    - "16686:16686" # Jaeger UI
    - "4317:4317" # OTLP gRPC endpoint
    - "6831:6831/udp" # Jaeger agent

  prometheus:
    image: prom/prometheus:latest
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
    - "9090:9090" # Prometheus UI

  ollama:
    image: ollama/ollama:latest # Example, replace with actual image if available
    environment:
    - MODEL_NAME=llama3.2
    ports:
    - "11434:11434" # Default port for Ollama API (adjust as needed)
    restart: always
